name: Builds, tests & co

on:
  pull_request:
  push:
  release:
    types: [created]

permissions: read-all

jobs:
  build:
    runs-on: "ubuntu-latest"
    services:
      postgres:
        image: postgres:15.6
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          PGUSER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6432:5432
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
      - name: Make migrations
        uses: emilpriver/geni@main
        with:
          migrations_folder: "./examples/postgres/migrations"
          wait_timeout: "30"
          migrations_table: "schema_migrations"
          database_url: "postgresql://postgres:postgres@localhost:6432/postgres?sslmode=disable"
      - name: Download and install dune
        run: curl -fsSL https://get.dune.build/install | sh
      - name: Add dune to PATH
        run: echo "$HOME/.dune/bin" >> "$GITHUB_PATH"
      - name: Build & run integration tests
        run: /home/runner/.dune/bin/dune runtest
